### ISSUE TITLE
Remove bitHound before May 30th, 2018

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/jstp#333]
`Please be advised that the bitHound service will be shutting down on May 30th, 2018.` // Dan Silivestru, CEO bitHound

**Comment by belochub** [comment]
After doing some searching, I think, we have two other similar services to migrate to, which are [Code Climate](https://codeclimate.com) and [Codacy](https://codacy.com). They both support JavaScript projects and seem to be free for open source projects. Also, from what I've read about its features Codacy looks more similar to the BitHound than Code Climate, so I think it's better to try out Codacy at first.

**Comment by tshemsedinov** [comment]
@belochub great, we will move all ours libraries to new quality monitoring tool, especially dependency checker. JSTP have Codacy registeration https://app.codacy.com/app/metarhia/jstp/dashboard but it have no appropriate dependency checker. On the other hand Code Climate allows just one free repository per account.

**Comment by belochub** [comment]
@tshemsedinov, I think GitHub can already be used as a somewhat reliable dependency checker.
It shows warnings about outdated and vulnerable dependencies on this page: https://github.com/metarhia/jstp/network/dependencies.

**Comment by aqrln** [comment]
@tshemsedinov, as @belochub mentioned above, checking for insecure dependencies that have CVE IDs is now built in to GitHub. Alas, it doesn't show the path in the dependency tree and doesn't indicate whether an item is a dependency or a devDependency.

For a broader security database (and probably better UX), we can use [Snyk](https://snyk.io), which [bitHound has relied upon](https://blog.bithound.io/bithound-integrates-with-snyk/), directly. Apart from monitoring, it can automatically open PRs with updated dependencies, when there are official fixes by package maintainers, or sometimes their own patches/backports. Speaking about automation, there's a popular service named [Greenkeeper](https://greenkeeper.io), which, whenever a new version of a dependency is published, tries to update it in a temporary branch, runs the CI, and, depending on the outcome, opens a PR or an issue.

Another vulnerability database and Snyk's main competitor — Node Security Platform — [has been acquired by npm](https://blog.npmjs.org/post/172793182214/npm-acquires-lift-security-and-node-security) recently. The new [npm 6](https://medium.com/npm-inc/announcing-npm-6-5d0b1799a905) already implements the client-side functionality and will start printing warnings on `npm install` and providing reports on `npm audit` as soon as the registry supports it on the server-side. And the CLI command to check for outdated dependencies — `npm outdated` — has received some refinements in the latest release too.

**Comment by aqrln** [comment]
A thing to keep in mind about Snyk: even though bitHound uses its vulnerability database, the result of analysis differs among them. At the moment, bitHound warns about deep insecure dependencies of GitBook, but a [quick run of Snyk](https://snyk.io/test/github/metarhia/jstp) (that's available for any public package/repo without enabling integration) shows no problems, because it only checks runtime dependencies and ignores devDependencies. The only way to analyze the devDependencies is by using the CLI (`snyk test --dev`). bitHound did that for us automatically. Furthermore, you might notice that GitHub warns about `hoek@2.16.3`, but bitHound doesn't, despite its (or, technically, Snyk's) database being bigger. This is the second pitfall: both Snyk and bitHound don't support package-locks/shrinkwraps. But running `npx snyk test --dev` locally warns about `hoek` too, because it analyzes the contents of `node_modules` directly. Keeping the current list of dependencies to be notified about vulnerabilities in up-to-date also seems to be manual. In other words, while bitHound just worked, Snyk requires some configuration and integration with the CI pipeline to be useful.

**Comment by tshemsedinov** [comment]
You know, I would prefer not to have dependencies at all :)

**Comment by aqrln** [comment]
UPD: `npm audit` is available in npm@5.10 too.
