### ISSUE TITLE
Add a possibility for client-side message logging before passing connection to client

### ISSUE THREAD

**Issue by belochub** [metarhia/jstp#349]
At the moment, there is no way to log messages on the client-side before the connection is being passed into callback of the `connect` and `connectAndInspect` methods, meaning that you can't log any of `handshake` or `inspect` messages being sent before the callback call.

I think we need to provide a way for the client to pass some kind of "logger function" into the aforementioned methods that will be called whenever the client is sending or receiving a message before this functions' callback call.

**Comment by belochub** [comment]
Ping @lundibundi, @nechaido.

**Comment by nechaido** [comment]
We can accept an event emitter and emit all logging events using it. If none is provided we can emit logging events on a connection.

**Comment by lundibundi** [comment]
Honestly, this looks like a hack and adds even more parameters to `client` object, but with our current logging strategy, I see no other way, so that may be it. I'd much prefer having usual pluggable logger via some general interface instead of using events, but that's not the route we have decided on before unfortunately.
